[tox]
envlist = py311,py312,py313

[testenv]
deps =
    .[dev]
commands =
    ruff check .
    ruff format --check .
    mypy .
    pytest --cov=apiflaskdemo --cov-fail-under=80 --junitxml=junit-{envname}.xml
